mode: delete
unlearning_model: gnndelete
gnn: rgcn
dataset: WordNet18
random_seed: 42
data_dir: ./datasets
checkpoint_dir: ./outputs/checkpoints
output_dir: ./outputs/results
df: out
df_size: 0.5
deletion_operator: relation_lora_moe
del_lora_base_mode: identity
loss_fct: mse_mean
loss_type: both_layerwise
loss_r_type: bce_rank_l2
alpha: 0.5
rank_same_relation: true
del_moe_num_experts: 4
del_lora_rank: 8
del_gate_emb_dim: 16
del_gate_mode: soft
del_gate_temperature: 1.0
epochs: 50
valid_freq: 2
batch_size: 1024
num_steps: 32
