mode: train
unlearning_model: original
gnn: rgcn
dataset: WordNet18
random_seed: 42
data_dir: ./datasets
checkpoint_dir: ./outputs/checkpoints
output_dir: ./outputs/results
batch_size: 1024
num_steps: 32
